services:
  # Service pour le frontend
  - type: web
    name: removal-ia-client
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false

  # Service pour le backend
  - type: web
    name: removal-ia-server
    buildCommand: |
      npm install
      cd server
      npm install
    startCommand: node server/server.js
    envVars:
      - key: MONGODB_URI
        sync: false 