services:
  # Service pour le frontend
  - type: web
    name: removal-ia-client
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: ./client/dist
    buildFilter:
      paths:
        - client/**
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false

  # Service pour le backend
  - type: web
    name: removal-ia-server
    buildCommand: cd server && npm ci
    startCommand: cd server && node server.js
    env: node
    buildFilter:
      paths:
        - server/**
    envVars:
      - key: MONGODB_URI
        sync: false 